#ifndef SCRIPT_GENERATOR
#define SCRIPT_GENERATOR

#include <stdio.h>
#include <string>
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>

using namespace std;

void GenerateFile(const vector<vector<Point> > &_contours, Chain &_chain, int &_num)
{
    ostringstream oss;
    oss << "../dextarFile/dextarFile" << _num << ".mp";
    std::string fileName = oss.str();
    ofstream file(fileName, ios::out | ios::trunc);  // ouverture en écriture avec effacement du fichier ouvert

    if(file)
    {
        cout << "Generation of the dextarFile, please wait..." << endl;

        file << "! Mecaprol progam auto-generated by the C++ code for portrait drawing using Dextar robot" << endl;
        file << "! Author: Alexandre Sarazin & Vamsi Krishna Guda, Date: June, 11 2017" << endl << endl;
        file << "START;" << endl;
        file << "!CFGLIN V40.0 A10000.0; ! [Optional] Speed and acceleration settings for MoveL, etc." << endl;
        file << "!CFGANG V360.0 A10000.0; ! [Optional] Speed and acceleration settings for MoveJ and MoveC." << endl << endl;

        file << "! Definition of the world coordinate system" << endl;
        file << "WCS X20.0 Y60.0 Z0.05 W0.0;" << endl << endl;

        file << "! Definition of the tool coordinate system" << endl;
        file << "TCS Z-42.5;  ! For the pen" << endl << endl;

        file << "! Go to initial position in the working mode of the home configuration (++)" << endl;
        file << "MoveC X25.00 Y-25.00 S100 M1; ! Pen is up by default" << endl << endl;

        Point p;
        for(unsigned int i=0;i<_chain.ordering_.size();++i)
        {
            // move to the first point to draw
            if(_chain.dir_[i])      p = _contours[_chain.ordering_[i]].back();
            else                    p = _contours[_chain.ordering_[i]].front();
            file << "MoveC X" << p.x << " Y" << p.y << endl << endl;

            // pen down
            file << "MoveZ Z2.0; ! Pen down" << endl;

            for(unsigned int j=0;j<_contours[_chain.ordering_[i]].size();++j)
            {
                if(_chain.dir_[i])
                {
                    file << "MoveC X" << _contours[_chain.ordering_[i]][_contours[_chain.ordering_[i]].size()-j-1].x
                            << " Y" << _contours[_chain.ordering_[i]][_contours[_chain.ordering_[i]].size()-j-1].y << endl;

                } else {
                    file << "MoveC X" << _contours[_chain.ordering_[i]][j].x
                         << " Y" << _contours[_chain.ordering_[i]][j].y << endl;
                }
            }
            // pen up
            file << "MoveZ Z0.00; ! Pen up" << endl << endl << endl;
        }

        file << "! Move DexTAR to its home configuration" << endl;
        file << "MoveZ L0.0" << endl;
        file << "MoveJ A0.0 B0.0" << endl;
        file << "END;" << endl;

        file.close();
        cout << "The dextarFile has been generated." << endl;
    }
    else
        cerr << "Impossible to open/create the dextarFile" << endl;
    file.close();
    cout << "Script has been saved in " << fileName << "." << endl;
}

#endif // SCRIPT_GENERATOR

